<?php

use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Routing\RouteMatchInterface;

use function Drupal\Core\Entity\t;

/**
 * Implements hook_help().
 */
function hello_world_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hello_world':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= 'This is an example module for custom module development';
      return $output;
 
    default:
      break;
  }
}

/**
 * Implements hook_mail().
 */
function hello_world_mail($key, &$message, $params) {
  switch ($key) {
    case 'hello_world_log':
      $message['From'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = 'Greeting message has been changed';
      $message['body'][] = $params['message'];
      $message['body'][] = \Drupal::token()->replace('Change made by [current-user:name]', ['current-user' => \Drupal::currentUser()]);
      break;
  }
}

/**
 * Implements hook_token_info().
 */
function hello_world_token_info() {
  $types = [
    'name' => t('Hello World'),
    'description' => t('Tokens related to the Hello World module'),
  ];

  $tokens['salutation'] = [
    'name' => t('Salutation'),
    'description' => t('The greeting message'),
  ];

  return [
    'types' => ['hello_world' => $types],
    'tokens' => ['hello_world' => $tokens],
  ];
}

/**
 * Implements hook_tokens().
 */
function hello_world_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = array();

  if ($type == 'hello_world') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'salutation':
          $replacements[$original] = \Drupal::service('hello_world.salutation')->getSalutation();
          $config = \Drupal::config('hello_world.custom_salutation');
          $bubbleable_metadata->addCacheableDependency($config);
        break;
      }
    }
  }
  return $replacements;
}

/**
 * Implements hook_theme().
 */
function hello_world_theme($existing, $type, $theme, $path) {
  return [
    'hello_world_salutation' => [
      'variables' => [
        'salutation' => NULL,
        'target' => NULL,
        'overridden' => FALSE,
      ]
    ]
  ];
}

/**
 * Default preprocessor for custom theme hook.
 */
function template_preprocess_hello_world_salutation(&$variables) {
  $variables['attributes'] = array('class' => array('salutation'));
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function hello_world_theme_suggestions_hello_world_salutation($variables) {
  $suggestions = array();
  if ($variables['overridden'] == TRUE) {
    $suggestions[] = 'hello_world_salutation__overridden';
  }
  return $suggestions;
}